version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/7.4"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/8.0"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/8.1"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
